// <auto-generated />
using System;
using Job.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Job.Migrations
{
    [DbContext(typeof(DBLocalContext))]
    [Migration("20200212202010_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Job.DBModel.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition");

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("FeelsLike");

                    b.Property<int>("Humidity");

                    b.Property<int>("PressureMM");

                    b.Property<string>("Season");

                    b.Property<int>("Temp");

                    b.Property<string>("WindDirection");

                    b.Property<int>("WindSpeed");

                    b.HasKey("Id");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("Job.DBModel.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 55.751379,
                            Longitude = 37.618853000000001,
                            Name = "Moscow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
